name: webportf
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  flutter_datetime_picker_plus: ^2.2.0
  google_maps_flutter: ^2.12.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  mailer: ^6.4.1
  email_validator: ^3.0.0
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  flutter_downloader: ^1.11.8
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/png/
    - assets/resume/
